workshop first commit
infuse-training-jan-2023/Practice-Dinesh pull request #3
Opened 2023-01-24 06:06 UTC by Dineshgawas64

2023-02-01 10:32 UTC, joyrel-vaz requested changes

2023-02-03 04:56 UTC, joyrel-vaz commented on workshop/test.rb
> +        element = obj.get_element_by_tag_name("inputtt")
Each unit test should test only **one** function. This unit test uses the `get_element_by_tag_name` method.

2023-02-03 04:58 UTC, joyrel-vaz commented on workshop/test.rb
> +        element = obj.get_element_by_tag_name("inputtt")
You can use the driver methods to get the text

2023-02-03 04:58 UTC, joyrel-vaz commented on workshop/test.rb
> +        element = obj.get_element_by_tag_name("inputtt")
Change other unit tests similarly

2023-02-03 07:37 UTC, joyrel-vaz commented on workshop/Selenium_Framework_2.rb
> +      @driver = Selenium::WebDriver.for :chrome, options: options
This driver can be passed into the constructor

2023-02-06 07:19 UTC, Dineshgawas64 commented on workshop/Selenium_Framework_2.rb
> +     end
i added sleep just to make automation slow down ,its  not waiting for any element

2023-08-23 07:08 UTC, closed without merging